# Dockerfile
FROM python:3.11-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo de dependencias
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Instalar dependencias necesarias
RUN apt-get update && apt-get install -y wget libgomp1

# Ajustar la zona horaria a Bogotá
ENV TZ=America/Bogota
RUN apt-get update && apt-get install -y tzdata && \
    ln -snf /usr/share/zoneinfo/America/Bogota /etc/localtime && \
    echo "America/Bogota" > /etc/timezone

# Copiar el resto de archivos de la aplicación
COPY . .

# Comando para iniciar la aplicación con Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "src.api.flask_app:app"]
